eg1_PCA_A-1.par<-as.matrix(c(64.5,54.3,50,10000,2.04,10.2,20,))
rownames(eg1_PCA_A-1.par)<-c("Instrument_Length of Capillary (cm)","Instrument_Length to Detector (cm)","Instrument_Inner Diameter (um)",
"Instrument_Voltage (V)", "Instrument_Idle Time (s)", "Instrument_Ramp Time (s)","Instrument_Temperature (C)","Chem_[A] in BGE (M)","Chem_[P] in BGE (M)","Chem_[A] in Sample 1 (M)",
"Chem_[P] in Sample 1 (M)","Chem_Sample 1 Plug Length (cm)","Chem_[A] in Sample 2 (M)","Chem_[P] in Sample 2 (M)","Chem_Sample 2 Plug Length (cm)",
"Chem_Distance Between (cm)","Stoich_Coefficient of A","Stoich_Coefficient of P","Stoich_Coefficient of C","Binding Constant","Association Rate (/s/M...)",
"Dissociation Rate (/s ...)","Equilibrium or Kinetic","mu_Free A","mu_Free P","mu_Complex C","mu_Electroosmotic Flow (EOF)","mu_Time of EOF Marker (s)",
"Migration Time of A (s)","mu_Viscosity Correction A","mu_Viscosity Correction P","mu_Viscosity Correction C","D_Species A","D_Species P","D_Complex C",
"Wall_[W] (mol/dm^2)","Wall_[W] Used in Calculation","Wall_Delay After Injection","Wall_Pre-equilibrated Wall","WA_Interaction",
"WA_Adsorption Rate","WA_Desorption Rate","WP_Interaction","WP_Adsorption Rate","WP_Desorption Rate","WC_Interaction",
"WC_Adsorption Rate","WC_Desorption Rate",
